### ISSUE TITLE
String.prototype.translate和fillData

### ISSUE THREAD

**Issue by yfdyh000** [vctfence/scrapbee#11]
两者的具体目的，能否加上些注释呢，比较难懂，以及有些担心其性能。建议用ES6的模板字符串``${var}``等代替。
fillData调用的escape，导致没法为侧栏中的右键菜单的label加`&`字符作访问键。

**Comment by vctfence** [comment]
好的, 我再想想哈, 可能要晚些处理, 能想到的是: ${var} 这种, 不适合用于非字面字符串吧, 比如来自 innerHTML.

**Comment by vctfence** [comment]
已注释
