### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by loosethisskin** [vctfence/scrapbee#14]
Hello vctfence. First of all I'd like to thank you for scrapbee, which is a great replacement for the good old scrapbook.

Below a few ideas/suggestions for improvements:

*   Sort rdf dropdown by name or option to re-order the rdf files in settings
*   Open captured pages in new tab with middle mouse click
*   Remove "Save success" message when saving settings
*   Enable auto scrolling of tree when moving saved pages with mouse up or down
*   Enable page capture by dragging tab to tree
*   Typo in delete confirmation dialog: "Realy delete the selected item?"
*   Push latest changes to github with every new release.
*   Possible to add build instructions to readme.md?

Thanks

**Comment by vctfence** [comment]
@loosethisskin  Thank you very much for provide suggestions, and I'd like to think about these ideas to improve ScrapBee in the future, by now I am not sure some of them can be implemented based on quantum and platform like Mac (e.g. 2 and 5)
