### ISSUE TITLE
Error in hierarchy for big scrapbook

### ISSUE THREAD

**Issue by Kerenok** [vctfence/scrapbee#15]
I have a big scrapbook with more than 13000 items and it's great that Scrapbee is able to open it! However, the tree hierarchy is messed up. At some point, a folder is inserted in the previous folder instead of being at the same level. It is inserted somewhere in the middle of the list.
* Foo
  * Foo1
  * Foo X
  * Bar
  * Foo X+1
  * ...

instead of
* Foo
* Bar

The RDF file has more than 600 folders and it's difficult to find what's happening! A backup version with 5000+ items for 270 folders doesn't seem to have the problem.

**Comment by vctfence** [comment]
@Kerenok  Thanks for report, I think it really hard to find the reason without a sample rdf file, what I can suggest for now is  trying to drag the bar folder out of the foo folder, if it saved and reloaded as expected, then the problem maybe be caused by some kind of error of the origin rdf file.

**Comment by Kerenok** [comment]
If I move Bar before Foo, everything is ok. Then if I move Bar after Foo, go to another RDF file then open the first one, the problem is back. I diff'ed the 2 version of the scrapbook.rdf files : the only difference is a line where the 2 RDF:li tags are swapped. Maybe Scrapbee is reaching some hardcoded limits in its data structures?

**Comment by vctfence** [comment]
@Kerenok I am going to release a new version in a few days, please wait a while to see if new version works for you.

**Comment by Kerenok** [comment]
Great! Thanks! I wanted to investigate the code but I found that the Github repo doesn't seem to have the latest version. 

While you're at it, maybe you could allow multiple selection (shift button and ctrl button) in tree.js? It helps for tidying up a large scrapbook by moving items in folders.

**Comment by Kerenok** [comment]
Using trials and errors, I found that the problem seems to be with an item title that ends with
` <link rel="` (it comes from the capture of an HTML code selection)

**Comment by vctfence** [comment]
@Kerenok Awesom! this looks an important clue, I'll take a look about this. and the code of new version is pushed now. For multiple selection, I need to consider if it can causes some kinds of conflicts.

**Comment by vctfence** [comment]
Hi, this have been here for a long time, sorry to be late, and I can not reproduce the problem so far, now close, please re-open if you still meet the problem.
