### ISSUE TITLE
How to capture pages?

### ISSUE THREAD

**Issue by clive0106** [vctfence/scrapbee#18]
I am using Linux mint 64bit. Firefox 67.0 64bit. ScrapBee 1.7.
I can import and view old Scrapbook data - thanks.
I cant figure out how to capture new pages.. The pretty B Button does not respond to Left-Mouse-Clicks :( The Right-Mouse brings up the configure options...
Am I doing something wrong?

**Comment by vctfence** [comment]
Hi, can you see help page? if not, please update to version 1.7.2, then refer to help age.

**Comment by clive0106** [comment]
Thank you, its all good now... Great work
