### ISSUE TITLE
Problem capturing PDF page

### ISSUE THREAD

**Issue by Kerenok** [vctfence/scrapbee#19]
Scrapbook can successfully capture PDF pages (for example, https://www.isprs.org/proceedings/XXXVI/5-C53/papers/FPL010.pdf ). In this situation, maybe Scrapbee should just send the raw file to the backend without trying to execute any script on the page (function scriptsAllowed).

**Comment by vctfence** [comment]
Hi, the problem is how we can know the url of a tab points to a pdf, I need to find out if there's a good way.
As I know we can not fetch anything about tab content with tab APIs.

**Comment by Kerenok** [comment]
Maybe doing a HEAD-request would allow to access the Content-Type of the page and save it accordingly?

**Comment by vctfence** [comment]
This should work, but not for all of the scenario I think, because url does not always = content, this is true even for normal html page, the content maybe chaged by js after html loaded.

**Comment by vctfence** [comment]
Now I suggest to download the pdf manually, open it with firefox and capture it as a bookmark
