### ISSUE TITLE
Suggestion : multiple selection in tree view of scrapbooks

### ISSUE THREAD

**Issue by Kerenok** [vctfence/scrapbee#21]
It would be nice to implement multiple selections in the tree view panel of scrapbook (similar to the old extension Scrapbook). It makes it easier to organise the scrapbook hierarchy by moving or deleting multiple items at a time.

**Comment by vctfence** [comment]
Thanks, I am also thinking about this, I need to re-design something for multiple selection maybe conflicit with some of current functions.

**Comment by vctfence** [comment]
Done in Node Mover
