### ISSUE TITLE
No such native application scrapbee_backend

### ISSUE THREAD

**Issue by leshy** [vctfence/scrapbee#23]
Hi, my scrapbee is unable to start, this is the log:

[info] ScrapBee version = 1.7.10
[info] browser = Firefox 66.0.4
[info] platform = Linux x86_64
[info] start backend service on port 9900.
[error] backend disconnected due to an error: No such native application scrapbee_backend

My platform was overriden as win_32 by some privacy related extension, I suspected this was the issue, so I've reset this setting in about:config, and re-installed the extension to no avail, I've also tried running a fresh firefox install as a different user, reaching this same error.

Any idea what to try next?

Thanks

**Comment by vctfence** [comment]
Hi, it seems you'v not installed backend by running install.bat? Or it met something error maybe, please redo install to see what happens.

**Comment by leshy** [comment]
ah! I'm sorry, I somehow missed the installation instructions in the app itself, everything good, and thanks for the fantastic project!
