### ISSUE TITLE
Could migration of Scrapbook X data be realized?

### ISSUE THREAD

**Issue by minshifu** [vctfence/scrapbee#24]
Thank you for your great work. Could you pls enable it to support "Scrapbook X" data? Best regards!

**Comment by vctfence** [comment]
I am guessing: it uses a  varietas of RDF maybe, It will be helpful for researching if you send me a sample ScrapbookX RDF which can be short but shows the problem.

**Comment by minshifu** [comment]
hi,pls check the original file of scrapbook x. Hope it'll be of help to you. 

[scrapbook-x-1.14.5.zip](https://github.com/vctfence/scrapbee/files/3401795/scrapbook-x-1.14.5.zip)

**Comment by minshifu** [comment]
不好意思，我才发现发错地方了哈哈，我给你发过邮件，讨论过scrapbee改进的问题 。我是点击下面的链接想发问题，但不想自动跳转你这里了 https://github.com/GChristensen/scrapyard/pulls   他的扩展在这里 https://addons.mozilla.org/zh-CN/firefox/addon/scrapyard/?src=search， 特点是无需打开左侧栏，可以通过popup界面来控制存储页面的文件夹结构，但是也还是有一些不足

**Comment by vctfence** [comment]
@minshifu 没关系， 出于一些原因， 不打算做成他那样的形式
