### ISSUE TITLE
Scrapbee stuck on "starting..."

### ISSUE THREAD

**Issue by raelb** [vctfence/scrapbee#25]
Hi. Just installed into Firefox.
Here is a picture:
![image](https://user-images.githubusercontent.com/13108198/61656448-0c81a780-acc1-11e9-8c51-c89a61ffff65.png)

Log:

[info] ScrapBee version = 1.8.2
[info] browser = Firefox 68.0.1
[info] platform = Win32
[info] start backend service on port 9900.
[error] backend disconnected due to an error: No such native application scrapbee_backend

I am on Windows 10 x64. Firefox is 68.0.1 (64 bit)
Any advice?
Thanks

**Comment by vctfence** [comment]
Hi, have you finished the install steps?

**Comment by raelb** [comment]
Actually I had not. Now I did follow the install steps. I still get an error:

![image](https://user-images.githubusercontent.com/13108198/62208625-b8995180-b397-11e9-8b7a-d941d333382d.png)

C:\Temp\test.rdf is a blank file

**Comment by vctfence** [comment]
Hi, please do not create the rdf file manually, it will check if the file exists, and ask you if you want to create the rdf (auto) in sidebar. please remove the rdf file you created at first and just visit it in sidebar.

**Comment by raelb** [comment]
Thanks for the help. It is working now!
