### ISSUE TITLE
Capture menu on the toolbar

### ISSUE THREAD

**Issue by cimfalab** [vctfence/scrapbee#26]
Hi,
I am using 1.8.2 version.
It works nicely as an alternative of ScrapBook.

I can find the capture menu only in the context menu on the page.
But some pages do not allow the mouse right-click operations, so I can't use the ScrapBee capture menu.

Is it possible to add the capture menu into the Firefox toolbar or ScrapBee sidebar's toolbar?

Thank you.

**Comment by vctfence** [comment]
Hi, it's really a problem, I'll do some research on it.

**Comment by cimfalab** [comment]
I tried some FF extensions enabling right click but none of those worked.
But when I just right click with SHIFT key, the context menu appears so captured the page!
What a simple solution..

**Comment by vctfence** [comment]
Hi, sorry to be late, ScrapBee has a "browser action" (toolbar menu) now, click on the ScrapBee icon, you'll see a "menu" pop up there, and you'll find same items as in context menu.
