### ISSUE TITLE
BUG: Scrabpee does not allow me to drag a saved page to a folder I created.

### ISSUE THREAD

**Issue by bulrush15** [vctfence/scrapbee#30]
Firefox v69 on Windows 10. 

Here are the steps to recreate the problem.

1. Install Scrapbee. 
2. Find a simple web page to save, choose "Capture Page" to save the page locally. 
3. On the Scrapbee sidebar, create a new folder. 
4. Now try to drag the saved page to the folder. I cannot drag the saved page to the folder.

**Comment by aleksejrs** [comment]
I can do it, but I need to target the folder's icon or title.

**Comment by vctfence** [comment]
I can not reproduce this problem so far, please check and re-open if you still meet the problem. Close for now.
