### ISSUE TITLE
backend port problem with multiple profiles

### ISSUE THREAD

**Issue by unalignedcoder** [vctfence/scrapbee#33]
I have 5 firefox profiles, scrapbee on all of them pointing to different scrapbee RDFs.

Until a couple of versions ago things worked. Now Scrapbee is broken.

The backend ports of the five profiles are configured as follow:
9900 9901 9902 9903 9904

In spite of this, with version 1.10.2 the log indicates 

`start backend service on port 9900.`

no matter the settings.

Except for the profiles where port 9900 is being used, this breaks scrapbee. The RDFs don't load (stuck at 'loading') and the log shows this message:

`[error] failed to start backend service: listen tcp 127.0.0.1:9900: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.`

It's probably unrelated, but the log also indicates

`[info] platform = Win32`

even though I am running scapbee_backend_64 on a Firefox 64

**Comment by vctfence** [comment]
Yes it loads wrong port from configuration, please try 1.10.3

**Comment by unalignedcoder** [comment]
I am reopening this issue because the problem is back. Same configuration as described above. Two of my 5 profiles work, on ports 9904 and 9903- The others display the message: "Failed to start backend. Please check installation and settings."

On such profiles installation and settings actually don't work. The option page only shows the titles of each section, but no content.

The scrapbee log reports:

`Listen Error: listen tcp 127.0.0.1:9902: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.` 

No reports for doors 9900, 9901 and 9905.

By the way, I am having problems finding the settings for the scrapbee opened doors. Where are they? I looked in all json, js and sqlite files I could think of.
