### ISSUE TITLE
Scrapbee stuck on "Starting..." after install, configure, and restart

### ISSUE THREAD

**Issue by balbirthomas** [vctfence/scrapbee#34]
Hi,
Scrapbee stopped working for me today. It is hung on "Starting..." (see screenshot below). 

![sb](https://user-images.githubusercontent.com/1672069/71850886-355df380-30cd-11ea-803a-6cf2af139f91.jpg)

This seems to be unlike the previous (now closed) bug of a similar nature that was reported here. I reinstalled scrapbee, reconfigured it (shown in screenshot) and restarted firefox. The problem still occurs. I checked the following 

1) Backend does launch successfully 
```
 $ netstat -tulnp | grep 9900
tcp        0      0 127.0.0.1:9900          0.0.0.0:*               LISTEN      2067/scrapbee_backend
```
2) Scrapbee log (in Scrapbee -> Settings) does not show any error
```
[info] ScrapBee version = 1.10.4
[info] browser = Firefox 68.3.0
[info] platform = Linux x86_64
[info] start backend service on port 9900.
[info] backend service started, version = 1.7.1 (wanted >= 1.7.0)
```
3) When I go to "scrapbee settings" then to "tools" both my RDF files are shown correctly and I can browse their folders correctly (see screenshot below)

![tools](https://user-images.githubusercontent.com/1672069/71850913-41e24c00-30cd-11ea-99e7-3bab4649c8a5.jpg)

However Scrapbee then "open in sidebar" just hangs on "{Starting...}"

I am not sure what else to check. Will appreciate any help here ? Is this a bug ?

**Comment by balbirthomas** [comment]
Hi,
Further to my issue report above, I found that Scrapbee Add-On in my browser seems to have auto-updated today (see screenshot below). Could this have caused the problem ? If so is there a fix/workaround for this bug ?
![upd](https://user-images.githubusercontent.com/1672069/71853538-a7393b80-30d3-11ea-8c15-123a22417d1f.jpg)

Thank you

**Comment by balbirthomas** [comment]
Removing the Mozilla Scrapbee Add-on completely and then reinstalling it (rather than just reinstalling the backend) fixed this problem. Not sure what went wrong. I am not able to reproduce it now. I will reopen this ticket if I can find how to reproduce it.

**Comment by Kerenok** [comment]
For me, the new version 1.10.5 fixed the problem
