### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by arnauldb** [vctfence/scrapbee#35]
Hello,

First thank you for this addon!

I have a problem with favicons as it fails to show them in the scapbee sidebar:
E.g. with this site: https://hyperallergic.com/542468/under-lockdown-and-quarantine-chinas-punk-rock-bands-are-taking-the-mosh-pit-online/
![2020-02-16_19-35](https://user-images.githubusercontent.com/13196747/74610494-a12f7500-50eb-11ea-848d-92e3fb7b3517.png)

I use version 1.10.5 with FF 72.0.0 on Linux Mint Sylvia.

The other favicons are from my old scrapbook files.

**Comment by vctfence** [comment]
Can not reproduce so far, how about it now?

**Comment by arnauldb** [comment]
It is solved, thank you.
