### ISSUE TITLE
Source code not up to date

### ISSUE THREAD

**Issue by Kerenok** [vctfence/scrapbee#36]
The source repository is way behind the current distributed version (1.8.4 rather than 1.10.6). It discourages people to contribute code or translations.

**Comment by merosss** [comment]
I'm also supporting this point. I would have like to contribute to the UI, but the last update on the addon is April 2020, while the last update here is from August 2019.

**Comment by scrap-hub** [comment]
I'm also supporting this point. Thank you if you are able and willing to hear user feedback.

**Comment by vctfence** [comment]
Sorry to be late, I pushed new version, thanks.

**Comment by Kerenok** [comment]
Thanks for pushing the latest version.
