### ISSUE TITLE
bookmark

### ISSUE THREAD

**Issue by arnauldb** [vctfence/scrapbee#37]
Hello,
Thank you for this addon. However I don't understand the bookmark functionality, how to use it, what is its usage? Is it the same as capture url which I don't understand either...
Except this it is working fine and I thank you again for this addon.

**Comment by Kerenok** [comment]
My understanding is that "Capture URL" is like bookmarks in the browser but allow you to organize them along this scrapped web pages for convience.

**Comment by arnauldb** [comment]
Ok, thank you.
