### ISSUE TITLE
Improve visibility of the properties popup

### ISSUE THREAD

**Issue by Kerenok** [vctfence/scrapbee#39]
Currently the popup to display the properties of a saved page or a saved URL is limited to the left panel dedicated to Scrapbee. As the left panel is ofter narrow to give more rooms to the web pages, the popup is truncated. Could it be opened at full sized above all panels or as a new window?

**Comment by scrap-hub** [comment]
No truncation of property popup with FF 76.0.1 where popup displays full size accorss l/h scrapbee and r/h webpage panes. Could it be we have different versions of ScrapBee or ScrapBee backend?

Wonderfull work by Scrapbee coder to bring Scrapbook back from the scrapheap - addon is soooo useful and functions soooo well. The documentation, however could do with a rework. I'd be happy to help with that.

**Comment by Kerenok** [comment]
Problem experienced with Firefox 76.0.1 and Firefox 77.0 on Windows 10, Scrapbee version 1.10.9 with backend 1.7.1

**Comment by scrap-hub** [comment]
How do you idendify which version of ScrapBee and/or backend is installed?

**Comment by Kerenok** [comment]
From left panel, go to Configure page (gear icon) then "Journal"

**Comment by scrap-hub** [comment]
To idendify version of Scrapbee and backend, I go
Settings/Log (on my version there is no "Journal)

![ScrapBee version](https://user-images.githubusercontent.com/65325177/84164334-4e971180-aa6a-11ea-8625-c5ec1af72426.jpg)

**Comment by vctfence** [comment]
This is really a pain in quantum world, as I know there's no way to generate a modal dialog natively.

**Comment by Kerenok** [comment]
Would it be possible to open a dedicated window (browser.windows.create) with a sufficient size to correctly display all the information?

**Comment by vctfence** [comment]
Hi @Kerenok, I saw some extensions show dialog in that way, but it's not modal dialog I want. The flow might become ugly such as situation when user switch to another tree while a properties dialog is opened. Now, while user submits, it must load the tree file into memory just for updating, can be slow for big trees. There may be extreme cases, such as user changed filename (or delete) the rdf while the dialog opened with node data of the tree then it becomes a "wild" dialog .
