### ISSUE TITLE
install.bat is fixed, it is not suitable for the modified download path

### ISSUE THREAD

**Issue by yfdyh000** [vctfence/scrapbee#4]

**Comment by vctfence** [comment]
能详细说明一下吗

**Comment by yfdyh000** [comment]
我的Firefox下载路径是手动设置的`D:\我的文档\下载`，下载得到的脚本不能用，排查了好一阵子。

另外，Windows 10下，`install.bat`（UTF-8）中手动填入我的中文路径，注册表项是乱码的。

**Comment by vctfence** [comment]
对于这个问题, 首先想到的是这个下载目录通常是英文的, 但是系统显示成中文,实际指定时,还需要中文,  如果不是这个问题, 也许windows需要的不是utf-8格式.

**Comment by yfdyh000** [comment]
`通常是英文的`，对修改了Firefox选项-下载的用户，该批处理不适用。

Windows cmd的默认编码是GBK，可能要做些处理。

**Comment by vctfence** [comment]
可能要用ANSI, 尤其还涉及其它国家语言比如日语

**Comment by yfdyh000** [comment]
经测，加一行`chcp 65001`设定代码页为UTF-8，就不会乱码了，显示也正常。
如果生成bat，可能也要注意字符编码。

**Comment by vctfence** [comment]
好的, bat 目前不是生成的, 但是有的场合可能需要用户自行编辑
