### ISSUE TITLE
Feature request: Output Tree as HTML

### ISSUE THREAD

**Issue by BlindB0** [vctfence/scrapbee#41]
Is it possible to implement this feature as it was in original [scrapbook](http://www.xuldev.org/scrapbook/features3.php)?
It will be usefull to export the whole collection into own server to access from everywhere.

**Comment by vctfence** [comment]
Possible in theory, but maybe not provide this in a short time.

**Comment by BlindB0** [comment]
Ok, thanks. I will wait.
By now I made it by install old firefox & old scrapbook, then export tree there.

**Comment by vctfence** [comment]
Hi, I pushed new code for "exporter", can you please try it in "debug mode"?
You can clone or download the code, disable the current scrapbee addon, 
then load the code in about:debugging#/runtime/this-firefox.

It's better to export the settings at first, because the settings may be removed sometimes.

![xxx](https://user-images.githubusercontent.com/47622351/89141188-51c2f100-d533-11ea-84e5-c3e3ca6235df.png)

![xyz](https://user-images.githubusercontent.com/47622351/89141219-6f905600-d533-11ea-92bd-ed1ff46ca5b6.png)

**Comment by vctfence** [comment]
![image1](https://user-images.githubusercontent.com/47622351/89142172-386f7400-d536-11ea-8af7-e8eb2ccb56c8.png)
![image2](https://user-images.githubusercontent.com/47622351/89142181-3dccbe80-d536-11ea-90e6-b2f16c3ec982.png)

**Comment by vctfence** [comment]
![image1](https://user-images.githubusercontent.com/47622351/89142911-48885300-d538-11ea-86c1-0f1866bc7d5b.png)
![image2](https://user-images.githubusercontent.com/47622351/89142915-4d4d0700-d538-11ea-8f56-d0fe29ff926a.png)

**Comment by BlindB0** [comment]
Hi!
I made it. But no luck in my case.
`
[info] version = 1.12.0

[info] browser = Firefox 79.0

[info] platform = Win32

[info] start backend service on port 9900.

[info] backend service started (caller: background), version = unknown (wanted >= 1.7.0)

[info] show rdf list

[info] switch to rdf "G:\dropbox\scrapbook\scrapbook.rdf"

[info] rdf loaded in 75ms
`
RDF shows fine in side panel, but no tool in Tool panel works.
I cannot choose source rdf to export tree.
![scrap2](https://user-images.githubusercontent.com/6443676/89165477-4ac2cf80-d581-11ea-8411-7d64d267291e.png)

Node Mover doesn`t see rdf either.

I can try it on ubuntu 20.04 x64 later.

**Comment by vctfence** [comment]
Hi, can you try to reload this page to see if it shows rdfs?

**Comment by BlindB0** [comment]
Completely empty profile, no custom options. Only ScrapBook extension.
English Firefox 79.0 (x64) this time, Win7 x64.
All the same after multiple reload page.
![scrap1](https://user-images.githubusercontent.com/6443676/89266578-c171d280-d63e-11ea-9b82-cd2035fd8270.png)

**Comment by vctfence** [comment]
Okey, the backend is outdated, please update. Then it will be 1.7.1 instead of unknown.

=> [info] backend service started (caller: background), version = **unknown** (wanted >= 1.7.0)

**Comment by BlindB0** [comment]
With updated backend it works just fine on rdf with over 600 nodes.
Thanks for your work!
Can you plz add fold/unfold feature to exported html? And favicons.

**Comment by vctfence** [comment]
All right, this is just a overview, suggestions are welcome.

**Comment by vctfence** [comment]
Please try my last push.

**Comment by BlindB0** [comment]
Last push works perfect. Fold/unfold and favicons.

**Comment by vctfence** [comment]
Released in version 1.12.1.
