### ISSUE TITLE
Difficulties saving images

### ISSUE THREAD

**Issue by arnauldb** [vctfence/scrapbee#42]
Hello,

First thank you for this addon I've been using for a while. Since a few days I have difficulties saving images when I save a web page (maybe since last scrapbee update??) e.g. : https://stories.rbge.org.uk/archives/28455 I don't have any saved images when saving the whole page: 

![555](https://user-images.githubusercontent.com/13196747/93238186-9962ac80-f770-11ea-87a8-b087d9687d66.png)

What can be wrong?
Here are my logs: [link](https://paste.eccologic.net/?36f0f27af604a2bd#Ghy8sZwjUG4NJWnVuuqPcJxXZnzwD1cTUPz4XcLxFzGs)

Thank you.

**Comment by vctfence** [comment]
Hi, I tried times on this page in a few days, seems all good, does it still not work for you?

**Comment by arnauldb** [comment]
> does it still not work for you?

Hi, thank you, it is working now. If I use scrapbee in a private window (with no other addons loaded) then scrapbee successfully save the whole page(s) and images. If I use scrapbee in my everyday firefox (with a few addons) then a lot of images aren't saved. Could it be that an addon prevent scrapbee to save images?

**Comment by vctfence** [comment]
Hi, possibly, it caused by one of your addons, I am afraid you need to disable all the other addons and plug them back one by one, to know which is it.
