### ISSUE TITLE
Error scrapbee_backend

### ISSUE THREAD

**Issue by i-mirror** [vctfence/scrapbee#43]
UBUNTU 20.04 scrapbee_backend: 1.7.3
scrapbee_backend: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found

**Comment by BlindB0** [comment]
Confirm.
Kubuntu 20.04
Last updated glibc is [2.31](https://packages.ubuntu.com/source/focal/glibc)
Version 2.32 only in ubuntu 20.10

**Comment by vctfence** [comment]
Hi, please compile backend for yourself if you like to:
env GOARCH=amd64 go build -o scrapbee_backend -ldflags "-s -w" scrapbee_backend.go
or
env GOARCH=386 go build -o scrapbee_backend -ldflags "-s -w" scrapbee_backend.go

You can find scrapbee_backend.go here:
https://github.com/vctfence/scrapbee_backend

**Comment by BlindB0** [comment]
Made it.
Works just fine.
Thanks!

**Comment by i-mirror** [comment]
Works fine.
Thanks!
