### ISSUE TITLE
Scrapbee stoped loading scrapbook's rdf

### ISSUE THREAD

**Issue by balbirthomas** [vctfence/scrapbee#44]
Hi

I have my scrapbee files and the old scrapbook files in separate directories (including their corresponding rdf files). In the scrapbee drop down menu I could select between the two . I am currently using scrapbee 2.1.0 with backend (from git) 1.7.3. I find the scrapbook option is no longer present in the dropdown menu. Nothing else has changed the scrapbee configuration is stil the same and both the paths (to rdf files) are valid.  I see no errors in the log. How can I debug this ?

Oddly enough. I do see "scrapbook" in the node mover tool but not in the dropdown menu. So I can trying moving nodes from old scrapbook to scrapbee but can not read the old scrapbook content. 

is there any way to merge my old scrapbook.rdf content into the new scrapbee.rdf and just move all the folders under "scrapbook/data/" into "scrapbee/data". ? I am hesitant to use the "node mover" tool because of the warnings listed on its page.

**Comment by vctfence** [comment]
Hi, so you have 2 rdf(s) set, and only 1 showed in sidebar dropdown list right?

If possible, can you show me your rdf setting?

Please feel free to use Node mover if you have backed up your rdf file and data folder.

**Comment by vctfence** [comment]
Hi, also, you can try to remove "scrapbook rdf" from settings and save. Then add it back and save to see if it appears.

You can even have repeated items in rdf settings.

**Comment by balbirthomas** [comment]
Hi ,

Yes I have 2 RDFs set and only 1 showed up in the sidebar drop down list !

Shown below is a screenshot of the RDF settings. The paths are correct since I copied and pasted them and rechecked them.
![rdf](https://user-images.githubusercontent.com/1672069/98033033-c9433d80-1e0c-11eb-89b6-1626a15b4d39.png)

I did remove the "scrapbook.rdf" clicked "save", shutdown the browser. After restarting the browser I added the "scrapbook.rdf" again clicked save and then shutdown the browser. After restarting i still see a single item in the drop down list.

Here is what the log looks like with both the RDF files set
```

[info] version = 2.1.3
[info] browser = Firefox 78.3.0
[info] platform = Linux x86-64
[info] start web server: port = '9900'. pwd = ''
[info] connect web server: connected, version = 1.7.3
[info] show rdf list
[info] switch to rdf "/home/bt/docs/scrapbee/scrapbee.rdf"
[info] rdf loaded in 135ms
[info] tools initiated successfully.
[info] tools initiated successfully.
```

The contents of `.mozilla/native-messaging-hosts/scrapbee_backend.json` is 

```
{
  "allowed_extensions": [
    "scrapbee@scrapbee.org"
  ],
  "description": "ScrapBee backend",
  "name": "scrapbee_backend",
  "path": "/home/bt/docs/scrapbee/scrapbee_backend",
  "type": "stdio"
}
```

The path to the scrapbee backend is correct.

The only other thing I have noticed is that in `/home/bt/docs/scrapbook` this is a `cache.rdf` . I do not know what it is and why it is there .

Let me know if you need any further information.

**Comment by vctfence** [comment]
Hi, can you export configuration (will be file named scrapbee_configure.json) and show me the content? You can find the export button beside save button.

And, please try to set more than 2 rdf(s) to see if there is still single item showed in the dropdown, 

thanks.

**Comment by vctfence** [comment]
Also, please try to set 2 rdfs without /home/bt/docs/scrapbook/scrapbook.rdf to see what happens.

**Comment by balbirthomas** [comment]
Hi, Here are the results -

1. [scrapbee_configure.json](https://github.com/vctfence/scrapbee/files/5490247/two_rdf_scrapbee_configure_json.txt) with scrapbee and scrapbook RDFs.

2. [scrapbee_configure.json](https://github.com/vctfence/scrapbee/files/5490253/three_rdf_scrapbee_configure_json.txt) with two scrapbee RDFs and one scrapbook RDF. The second and third items (`scrapbook` and `test`) were not shown in the drop down menu. Configuration shown below

![threerdf](https://user-images.githubusercontent.com/1672069/98162292-1260c380-1ed9-11eb-8b27-42cace595c99.png)

3. After removing `scrapbook.rdf` and adding a second `scrapbee.rdf`(as shown below), I still did not see the second item (`test`) in the drop down menu.

![without_scrapbook](https://user-images.githubusercontent.com/1672069/98162468-4fc55100-1ed9-11eb-9f1a-b0701579737e.png)

I always shutdown and restarted the browser after saving each configuration change. After starting I always checked that the new configuration was in effect.

**Comment by vctfence** [comment]
Hi, sorry for I can not reproduce the problem so far.

To know what causes the problem, I pushed new version with "debug log" to get more clue.

Please try Scrapbee from code with this new feature. Please refer https://github.com/vctfence/scrapbee/wiki/Debug for loading add-on from code.

This is what I see:

![vvv](https://user-images.githubusercontent.com/47622351/98181439-41f5e700-1f3e-11eb-9522-1f9f513d008c.png)
![uuu](https://user-images.githubusercontent.com/47622351/98181441-43bfaa80-1f3e-11eb-8c91-8c27a32c49b6.png)

**Comment by touwys** [comment]
Hi Victor

Thanks for your email.

Please read my notes on the attached screenshot which I took when I tried to figure out how to install the debug code. I am afraid I am not capable of doing that. I could also not interpret the two screenshots you published.

Thank you for trying. Hopefully, there is another way of doing this?

Pierre 

-----Original Message-----

**Comment by vctfence** [comment]
Hi Pierre,

Please click "New issue" to create another issue for your topic, create new topic for each issue: such as a wish or a problem.

**Comment by touwys** [comment]
Yes, thank you, I saw that posted my reply in error.

**Comment by balbirthomas** [comment]
Hi Victor,

I am not sure if I have understood what you need. But I did select the "debug" checkbox in Scrapbee -> Settings -> tool, then restarted the browser and opened the Scrapbee menu. Then I browsed to `about:debugging#/runtime/this-firefox` and clicked on "inspect" button beside the Scrapbee item. It brought up Firefox developer tools. I took a screenshot of the errors shown in the developer console window and am pasting it below. Is this what you needed ? If not please clarify what are the steps to capture a full debug log and I will gladly provide them. 

![debug](https://user-images.githubusercontent.com/1672069/98487296-10b93780-221a-11eb-8892-7b08ea420f6a.png)

**Comment by vctfence** [comment]
Hi, for now, please just update to version 2.1.4, and make sure Configure->Behavior->Debug is on. Then go to log (Scrapbee's own log) to see debug log about the drop down like below:

(https://user-images.githubusercontent.com/47622351/98181439-41f5e700-1f3e-11eb-9522-1f9f513d008c.png)

**Comment by balbirthomas** [comment]
Hi Victor, Thank you for clarifying. Attached is Scrabee log. 

![debug](https://user-images.githubusercontent.com/1672069/98726961-1b490d80-238f-11eb-8287-6905853552c7.png)

The paths in the log are correct and those RDF files exists at those paths. However the drop down menu only shows me "Scrapbee" but not "Scrapbook".

**Comment by balbirthomas** [comment]
Victor I think I have made a mistake. I just realized I am able to access scrapbook using the smaller dropdown (lower right corner of the screenshot below). All this while I was trying to use the drop down in the upper left corner. I do remember always using the dropdown in the upper left corner (beside the the Scrapbee icon) to switch between the two RDFs. My sincere apologies. 
However no matter which I select "Scrapbook" or "Scrapbee" the drop down in the upper left corner always show a tick mark beside Scrapbee and does not show "Scrapbook" at all.
![scrapbook](https://user-images.githubusercontent.com/1672069/98727683-39633d80-2390-11eb-8c5e-27751c982b38.png)
If the behavior is as intended then kindly accept my apology and close this bug or permit me to do so.

**Comment by vctfence** [comment]
Hi Balbir,  no problem, and any questions are welcome. But I don't quite understand what you mean. 

I guess, you think there should be a list box to select RDFs. But here's a dropdown "button", that's why tick mark showed. A list(menu) will be showed when you click on the button, and you can switch between RDFs there. Once you select an item, the list(menu) hides just like a traditional dropdown:

![dropdown](https://user-images.githubusercontent.com/47622351/98744931-89bcb880-23ed-11eb-91ee-c7eb3204cc8b.png)

Let me know if you still have problems, thanks.
