### ISSUE TITLE
Sidebar: Alphanumerical/Title Sort Error

### ISSUE THREAD

**Issue by touwys** [vctfence/scrapbee#46]
_Scrapbee v2.1.4 • Firefox v82.0.3 • Windows 7_

The **title** sorting behaviour of the Sidebar Nodes using the Context Menu does not seem follow the alphabet-sorting rules correctly. Should words contained in brackets not be sorted before words not in brackets? Please have look at the following error report:

![Scrapbee Sorting](https://user-images.githubusercontent.com/65730626/98664988-bcb26e00-2353-11eb-9565-c5b2600edca8.gif)

**Comment by vctfence** [comment]
Hi, this is not v2.1.4, please update, the sorting dialog will looks like:

![sort-dlg](https://user-images.githubusercontent.com/47622351/98746341-3ef07000-23f0-11eb-8c06-cbb6e7850b33.png)

**Comment by vctfence** [comment]
Here is my testing record
![Peek 2020-11-11 07-42](https://user-images.githubusercontent.com/47622351/98747041-abb83a00-23f1-11eb-9c22-8926c313789b.gif)
:

**Comment by touwys** [comment]
Thank you, I see that your test is correct.

However, according to my Scrapbee-log, I am indeed on v2.1.4 — just as I indicated in the screesnhot below. What should I do next?

![Scrapbee Default Version Number is v2 1 4 According to the Log](https://user-images.githubusercontent.com/65730626/98811282-441de100-2429-11eb-9188-8961b1c203f6.png)

**Comment by vctfence** [comment]
Hi, have you multi editions of Firefox or multi profiles enabled?

Please make sure to test the sorting function with right version of Scrapbee.

Or to be simple, just export you settings and reinstall Scrapbee addon (no need to reinstall backend).

**Comment by vctfence** [comment]
If it still does not work, you can try my latest commit (download code here) to see if developing version works for you.

**Comment by touwys** [comment]
> Hi, have you multi editions of Firefox or multi profiles enabled?

No, on both accounts.

> Please make sure to test the sorting function with right version of Scrapbee.

How does the user tell which one is the correct version, if, as in my case, it does display the correct version i.e. v2.1.4?

> Or to be simple, just export you settings and reinstall Scrapbee addon (no need to reinstall backend).

Thank you, I exported the settings, and then reinstalled Scrapbee. **Now, the sorting works just fine**. BUT, notice in the below screenshot that the radio buttons of the sort window differs from those of yours above.

![image](https://user-images.githubusercontent.com/65730626/98914452-5ce1d180-24d1-11eb-81d1-bc56d0581256.png)

**Comment by touwys** [comment]
> If it still does not work, you can try my latest commit (download code here) to see if developing version works for you.

As explained in the preceding message, the sorting now works — although the appearance of the sort-window is different to yours. 

Is it worthwhile to install your latest commit just for a cosmetic change? If you feel the code-installation is indeed essential, please provide the exact steps required to install the latest commit. It is already downloaded in anticipation of your further instructions.

Thank you.

**Comment by vctfence** [comment]
Hi, do you mean that you can not see Case Sensitive checkbox? Really weird, it's already in version 2.1.4, users should see exactly same thing if same version installed.

Load temporary addon is not essential step here, but no harm to have a try.

Please refer to wiki for the steps.

**Comment by touwys** [comment]
> Hi, do you mean that you can not see Case Sensitive checkbox? 

No, that is not what I meant. I see exactly what you can see in the screenshot I provided in the 3rd message above. The "Case Sensitive" checkbox is indeed visible. 

Here is my screenshot again — this time with yours directly below it. You will notice that they differ in appearance only — please look at the colours of the radio buttons...

![image](https://user-images.githubusercontent.com/65730626/99066280-60e52080-25b1-11eb-916e-26ece02c3f1f.png)
![image](https://user-images.githubusercontent.com/65730626/99066444-a570bc00-25b1-11eb-9ed3-1e3cd6549a3d.png)

**Comment by vctfence** [comment]
Well, I use Linux as daily system, it's natural to see different control theme in different OS, just like using different themes in windows.
