### ISSUE TITLE
Feature Request ♦ Sidebar: Adding and Placing New Root Folders

### ISSUE THREAD

**Issue by touwys** [vctfence/scrapbee#50]
At the moment, a new folder adds as a root node to the bottom of the tree.

_Proposed feature:_ 

Select any existing main tree folder, and then insert the new folder as a root node either directly above or below it.

**Comment by touwys** [comment]
@vctfence 

Expanding on the above request:

The same feature should apply to folders being added to the "current" position in folders containing multi-subfolders — Right-click on a folder to position a new one either directly above or below it.

Adding new folders is a highly used function of Scrapbee, and it appears to me that it should be viewed as a basic level function worthy of assuring early on in a commit, if you will. 

Thank you.

**Comment by vctfence** [comment]
Have you try "same level" already in current commit?

**Comment by touwys** [comment]
Yes, thank you, I am trying it. My comments:

The positioning of the new folder is unoriented. Therefore, I don't remember whether the new folder is going to be inserted above or below the current level/selected folder. This leads to misplaced folders that have to repositioned, which is an unnecessary extra step. Please consider changing this activity by adding the option to choose between inserting the new folder either above or below the chosen level/folder, and change the wording/text to read, for example:

"Insert new folder above selected"
"Insert new folder below selected"

Another small error I have noticed, is that the cursor misaligns when the New Folder box is opened. Vertically, it starts to flash below the centre-line of the text box.

**Comment by touwys** [comment]
`Another small error I have noticed, is that the cursor misaligns when the New Folder box is opened. Vertically, it starts to flash below the centre-line of the text box.`

Fixed. thank you.
