### ISSUE TITLE
Feature Request ♦ Save All Tabs in the Same Sequence They Open in the Browser 

### ISSUE THREAD

**Issue by touwys** [vctfence/scrapbee#61]
By default, please have all the tabs which are open in the browser, be saved in the same sequence they are displayed in the tab bar. (Possibly, optionally, add a means to have them saved in reverse order).

**Comment by vctfence** [comment]
This can be done, but will slow down the tasks, currently, it broadcast the "command" to all tabs, and make the order based on sequence of respond.

**Comment by touwys** [comment]
Agreed, I did guess that to save the tabs in sequence, would slow down the saving process. By how much, though? Although the current process is mostly sufficient, there are certain circumstances that make sequential saving of multi-tabs worth having. May I propose that you consider adding a configuration-option to accomodate sequential tab-saving?

**Comment by vctfence** [comment]
I'll have a try, but this will be low  priority。

**Comment by touwys** [comment]
This feature is highly desirable. Tab add-ons such as "[Open Multiple URL's](https://github.com/htrinter/Open-Multiple-URLs)" adds multiple tabs in the desired user-sequence correctly for a reason. Furthermore, this sequence can then be manipulated according to user-preference by add-ons such as ["Sort Tabs"](https://addons.mozilla.org/en-GB/firefox/addon/sorttabs/). It makes no sense then, to have Scrapbee defeat these user efforts by saving such well-prepared tabs, randomly, even if the process is marginally faster. If speed is essential, at least provide a user-option for choosing between one of two methods i.e. random fast saving, or, sequential tab saving at slightly slower speed.

> I'll have a try, but this will be low priority。

**If you would, please upgrade your priority for this feature?**

**Comment by touwys** [comment]
@vctfence 

Fixed in 2.6.1. Thank you very much.
