### ISSUE TITLE
Commit Issue ••• Node Mover Tool: Moving Files Error

### ISSUE THREAD

**Issue by touwys** [vctfence/scrapbee#64]
First observation: There is not method available in this commit to Multi-select files?

Secondly, the new progress indicator looks good and works well, thank you!

Thirdly, the issue: When files are moved from source, they do not show up at their destination:
•
•
•
•
•
![NMT Files Move_Disappear at Source   Do NOT Show Up at their Destination](https://user-images.githubusercontent.com/65730626/100220620-4c454880-2f20-11eb-81fd-14a125b61ef8.gif)

**Comment by touwys** [comment]
Here follows another example:
•
•
•
•
•
![NMT Files Move_Disappear at Source   Does NOT Appear at the Destination2](https://user-images.githubusercontent.com/65730626/100222123-4d777500-2f22-11eb-9d0d-0ee9fd238866.gif)

**Comment by vctfence** [comment]
Ok, there's a bug for moving, let's try copy at first. See multi-selection with SHIFT+click:

![nmt](https://user-images.githubusercontent.com/47622351/100293156-bf50cc80-2fbd-11eb-8f22-2fea0242461d.gif)

**Comment by touwys** [comment]
Copy Files = √

Shift + Click Multiselect = √

**Comment by vctfence** [comment]
Moving should have been fixed in commit https://github.com/vctfence/scrapbee/tree/1a1f0318dd1b1639062159fddd809e47da8ed576

**Comment by touwys** [comment]
`_Moving should have been fixed in commit 1a1f031._`

I confirm that moving nodes between the two NMT panels/trees is now fixed — thank you.

It is, however, impossible to move — or copy — nodes to the **_root_** of the target panel, under these conditions:

1. While a node is selected/active in the target panel, but its radio-button is not enabled.

2. While there are no files occupying the root. 

I could not figure out out how to deselect the active node in the target panel to activate the root. If such a function is not yet available, please consider this: 

Move or copy files only on condition that a radio-buttion is enabled in the target panel. Merely selecting a node (i.e with the radio-buttons disabled) shoud not justify the move/copy action. If there are no files occupying the root of the target panel, merely click on an empty space inside the panel to deselect an active node having a disabled radio-button.
•
•
•
![!NMT Moving Files To Root Deselect](https://user-images.githubusercontent.com/65730626/100434530-4d53b280-30a5-11eb-886b-7713711f8ead.gif)

**Comment by vctfence** [comment]
Try ed63d2dff0caa4e5283c3, which show root node always.

**Comment by touwys** [comment]
Hello Victor,

 

OK, that is a quick and good solution for me, but keep in mind that not everybody knows what "root" means, and what it is there for.

 

I also noticed that the folder that are getting moved do arrive at the target panel, but it still leaves a "blank" copy of each file at the source panel. These "blanks" plainly open on a browser page that reads: "404 page not found". Has this not been fixed in  <https://github.com/vctfence/scrapbee/commit/ed63d2dff0caa4e5283c39acabe44b0cf764e16d> ed63d2d?

 

Pierre

**Comment by vctfence** [comment]
>> leaves a "blank" copy of each file

Please discuss problems in their own issue.

**Comment by vctfence** [comment]
Pushed 510f7a16e30c142d32b3f19f1ed0eb88f21a88fc, let user toggle visibility of root node, should be enough.

**Comment by touwys** [comment]
I see d33bc70?

**Comment by touwys** [comment]
Checked, but although it works, it's still too "complicated" for something that doesn't really need such a complex way just to deselect a node. Is it impossible to get the app to simply deselect the more intuitive way, by simply clicking in an empty space in the panel?

(Note: Commit d33bc70 has not yet fixed the file move issue? Is that correct?)

**Comment by vctfence** [comment]
Commit for this issue includes just changes for this issue (usually), please discuss current issue here. 

We have talked about the disadvantage of deselecting nodes, and I think showing a root node is an even more clear/friendly/convenient method and I think it's easy to understand.

**Comment by vctfence** [comment]
In fact, if you try Scrapbook(for Firefox <= 52), you'll find the author think in same way, the focus won't lost when user click on empty space of sidebar.

**Comment by vctfence** [comment]
Also, you can see root node in Scrapbook, while selecting saving position:

![VirtualBox_win7-64-pure_08_12_2020_14_11_20](https://user-images.githubusercontent.com/47622351/101447831-f67d9100-3960-11eb-954c-41b84f89a37f.png)
![VirtualBox_win7-64-pure_08_12_2020_14_13_33](https://user-images.githubusercontent.com/47622351/101447840-f9788180-3960-11eb-8ff9-d14f2cf9faae.png)

**Comment by touwys** [comment]
Scrapbook is a mature app, and a very good example to emulate.
