### ISSUE TITLE
NMT Move Files Error ••• scrapbee-scrapbee-ed63d2

### ISSUE THREAD

**Issue by touwys** [vctfence/scrapbee#67]
Node Mover Tool:

When files are being moved between two panels, all the files do get moved to the target, but a copy of each are left behind at the source i.e. they are being copied instead of moved.

**Additional Note:** The files seem to have been physically moved from the source to the target, because the copies that are left behind at the source, are void of any original content.

**Comment by vctfence** [comment]
Can you explain a bit? What get copied? It seems all okay for me.

**Comment by touwys** [comment]
I hope the following animation provides the information that you are looking for. This is for commit scrapbee-ed63d2.

![NMT Moving Files Leaves Blank Copies Behind in Source Panel](https://user-images.githubusercontent.com/65730626/101282592-b8586400-37de-11eb-9c42-22510f314a1c.gif)

**Comment by vctfence** [comment]
Pushed 5a411ecfa4fd608eadf1cfb14442438921a19ef1 as fixing.

**Comment by touwys** [comment]
Fixed, thank you.
