### ISSUE TITLE
删除确认对话框出不来

### ISSUE THREAD

**Issue by yfdyh000** [vctfence/scrapbee#7]
记得之前版本是正常的，1.3.2（源码）和1.3.3（AMO）似乎不行了。
`TypeError: $dlg.html(...) is undefined main.js:71:15`

**Comment by vctfence** [comment]
确实, 引入了新的Bug, 已修改, 并更新到 1.3.5

**Comment by yfdyh000** [comment]
我做了补丁和拉取请求……
`menulistener.onDelete`的`confirm("warning".translate()`我猜你改错了，那个是title。

**Comment by vctfence** [comment]
谢谢, 这几天太忙, 以后尽量避免过频密的修改.
