### ISSUE TITLE
Order of captured pages

### ISSUE THREAD

**Issue by Kerenok** [vctfence/scrapbee#71]
When saving multiple pages in a row, they are listed in reverse order. It would be more natural to change the selected page in the list to the last saved page so that all pages would be in a sequence consistent with the "New items" option set to "Bottom".

**Comment by touwys** [comment]
If you are perhaps using Firefox as your browser, you could put the following web-extension to good use as well:

**[SortTabs](https://addons.mozilla.org/en-GB/firefox/addon/sorttabs/)**

**Comment by Kerenok** [comment]
Fixed with the option to add new items at top or bottom
