### ISSUE TITLE
Sidebar context menu partially displayed

### ISSUE THREAD

**Issue by Kerenok** [vctfence/scrapbee#78]
When right-clicking on a item in the lower part of the sidebar (scrolled down to the bottom), the context menu position is too low and some menu actions are not visible (for example Delete).
![Scrapbee_left_panel_menu_problem](https://user-images.githubusercontent.com/18365378/106724270-519dce00-6608-11eb-8dab-8f5129b2ded8.jpg)

Scrapbee 2.2.5 - Wndows 10 - Firefox 85.0

**Comment by vctfence** [comment]
It's not a real menu, impossible to take it out of the window, Firefox stopped to support custom context menu, now I can just provide a fake one(HTML div).

**Comment by vctfence** [comment]
I'll try to improve the position (within the window) later.

**Comment by vctfence** [comment]
Should have been fixed in version 2.2.6.

**Comment by touwys** [comment]
This is now fixed, thank you, but the following was not— 

Previously, when this "Properties" dialoque was opened, the "Title" field was auto-selected by default. Currently, the tree on the background gets auto-selected instead, which prevents any immediate action to be executed in the "Title" field. 

Please have a look at the screenshot below:
•
•
•
![image](https://user-images.githubusercontent.com/65730626/107616763-59d4b980-6c57-11eb-9c80-e949213784f3.png)

**Comment by Kerenok** [comment]
Thanks for rapidly fixing this. 

I wanted to know how this can be done in the source code but the Github repo is outdated.

**Comment by vctfence** [comment]
New commits pushed.
