### ISSUE TITLE
saved page problem 

### ISSUE THREAD

**Issue by i-mirror** [vctfence/scrapbee#82]
**LINK PAGE:** https://www.elettronew.com/it/accessori-tv/illuminatore-lnb-fte-single-universale-rhqsingle-27432.html

###############################################################################################
###############################################################################################
###############################################################################################

 **ORIGINAL PAGE:**
###############################################################################################

![Screenshot_2021-05-29 Illuminatore LNB FTE Single Universale RHQSINGLE](https://user-images.githubusercontent.com/7964751/120071940-9bb42f00-c091-11eb-9070-8e5eae047efb.png)

###############################################################################################
###############################################################################################
###############################################################################################

**SAVED PAGE:**
###############################################################################################

![Screenshot_2021-05-29 Illuminatore LNB FTE Single Universale RHQSINGLE(1)](https://user-images.githubusercontent.com/7964751/120073383-4f202200-c098-11eb-9850-af69a4e3b94a.png)

**Comment by vctfence** [comment]
This is fixed in recent versions as tested for me, 2.5.7 for example.

**Comment by i-mirror** [comment]
Thank you.
