### ISSUE TITLE
Scrapbee popup not displayed correctly

### ISSUE THREAD

**Issue by GarenKreiz** [vctfence/scrapbee#87]
The menu is not formatted correctly (see image, text in French rather long, font too big). I could propose a pull request to fix the CSS but the Github repository is some versions behind the extension available on addons.mozilla.org (2.3.6 instead of 2.4.8).

![Scrapbee_problem](https://user-images.githubusercontent.com/1534636/147572252-ca455d7e-435b-4de0-884a-e74b0ab704c7.jpg)

**Comment by vctfence** [comment]
Thanks, I can not connect github for months, I'll try more to see if I can push the code.

**Comment by vctfence** [comment]
Hi, the repo updated to the last commit.
