### ISSUE TITLE
Popup menu in sidebar staying displayed

### ISSUE THREAD

**Issue by Kerenok** [vctfence/scrapbee#92]
When one want to choose where the next page will be saved, one can right click on a tree item in the sidebar (as left clicking opens the saved page by default). The item is selected but the popup menu stay displayed. To make it disappear, one has to click on Properties then on Cancel. It's a bit tedious.

**Comment by vctfence** [comment]
Noticed, but I found no event raised when user click outside the sidebar. So far, you can click somewhere out of the menu (in sidebar), no need to open Properties.
![2022-02-14_14-52](https://user-images.githubusercontent.com/47622351/153814792-2faf8e68-0a16-4541-b94c-657e3f6b0409.png)

**Comment by vctfence** [comment]
To hide menu when user click outside,
How do you think use window.blur? For me, it's a more rational way: hide menu while clicking.

**Comment by Kerenok** [comment]
Thanks for investigating. The workaround of clicking outside the popup on an empty zone does work : in some of my use cases where I minimize the width of the sidebar, the only empty zone at the left of the favicons of items and I had missed it!
