### ISSUE TITLE
使用記號筆（marker）時出現「没有激活选区」（No Selection Activated）錯誤

### ISSUE THREAD

**Issue by fweng322** [vctfence/scrapbee#97]
不知道從何 Firefox 版本開始，使用 ScrapBee 儲存頁面沒有問題。叫出儲存頁面，要用記號筆畫重點時，我先選擇要畫記號的文字，然後選擇下面的「記號筆」，選擇一種樣式，但出現：

localhost:9000
没有激活选区

這樣的錯誤訊息。Scrapbee 版本沒有更新過，推測可能是 Firefox 版本更新造成的。

**Comment by fweng322** [comment]
Firefox 版本：101.0.1
ScrapBee 版本：2.5.11 (最近更新時間：2022/10/8)

**Comment by vctfence** [comment]
我自己的正常， Firefox 版本 109，请检查是不是所有的页面都是如此。

**Comment by fweng322** [comment]
> 我自己的正常， Firefox 版本 109，请检查是不是所有的页面都是如此。

後來發現是我用 Scrapbee 截下 Google 圖書的頁面時才會有這種情形。可能 Google 圖書本身就有記號筆的功能。
